### ISSUE TITLE
Tarball?

### ISSUE THREAD

**Issue by devrimgunduz** [munakoiso/logerrors#3]
Hi,

I'd like to build RPMs of this extension in the official PostgreSQL RPM repository. I need a tarball for that. Can you please wrap it up?

Thanks!

Regards, Devrim

**Comment by munakoiso** [comment]
Hi!Sure, I'll wrap it up until the end of the week.Best wishes, Sviatoslav Ermilin.29.07.2020, 13:03, "Devrim Gündüz" <notifications@github.com>:
Hi,
I'd like to build RPMs of this extension in the official PostgreSQL RPM repository. I need a tarball for that. Can you please wrap it up?
Thanks!
Regards, Devrim

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sviatoslav Ermilin

**Comment by munakoiso** [comment]
Hi!

Sure, I'll wrap it up until the end of the week.

Best wishes, Sviatoslav Ermilin.

**Comment by munakoiso** [comment]
Hi, @devrimgunduz 
Release with tar is posted.

**Comment by devrimgunduz-edb** [comment]
Thanks a lot!

**Comment by NikolayS** [comment]
@devrimgunduz-edb I see that [you've created RPMS and published to the PGDG repo](https://git.postgresql.org/gitweb/?p=pgrpms.git;a=tree;f=rpm/redhat/13/logerrors;h=e686521e7b63730621a0afc962432b8dedfc54bd;hb=HEAD) – thanks a lot! – but what about .deb/apt, who could do it?

**Comment by devrimgunduz-edb** [comment]
Christoph Berg is responsible for APT repos.
